#!/bin/bash

if [ "$#" -lt 2 ] ; then
  printf "srcset generates scaled-down versions of an image and the corresponding <img srcset=\"...\"> HTML.

Usage: srcset <path-to-image> <width> <width> ...\n" >&2
  exit 1
fi

src_path="$1"
src_width=`identify -format "%w" "$src_path"`

basename=$(basename "$src_path")
filename="${basename%.*}"
extension="${basename##*.}"

tmp_file=srcset_tmp."$extension"

copied=false
shift

while test ${#} -gt 0; do
  target_width="$1"

  if [ "$src_width" -le "$target_width" ]; then
    if $copied; then
      shift
      continue
    fi
    copied=true
    cp "$src_path" "$tmp_file"
  else
    convert "$src_path"  -resize "$target_width" "$tmp_file"
  fi

  tmp_width=`identify -format "%w" "$tmp_file"`
  tmp_height=`identify -format "%h" "$tmp_file"`
  target_file="$filename"_"$tmp_width"x"$tmp_height"."$extension"
  mv "$tmp_file" "$target_file"
  srcset="$srcset$target_file ${tmp_width}w,\n  "

  if [ "$src_width" -le "$target_width" ]; then
      printf "Generated $target_file (full-size copy)\n"
  else
      printf "Generated $target_file\n"
  fi

  shift
done

srcset=${srcset%,*}
img="<img srcset=\"$srcset\"\n  sizes=\"\"\n  src=\"$src_path\">"

printf "\n$img\n"

# OS X only
if command -v pbcopy >/dev/null 2>&1; then
  printf "$img" | pbcopy
  printf "\n<img> copied to clipboard.\n"
fi
